---
services:

  deploy:
    platform: 'linux/amd64'
    build:
      context: .
      target: app
    ports:
      - "80:5000"
    environment:
      - NUM_WORKERS=6
    env_file:
      - path: ./.env
        required: false
    volumes:
      - ./logs:/tmp/logs
    restart: always

  dev:
    platform: 'linux/amd64'
    build:
      context: .
      target: app
    ports:
      - "1986:5000"
    environment:
      - AUTO_RELOAD=true
      - STATIC_CACHE_TIME=0
      - NUM_WORKERS=1
    volumes:
      - ./src:/var/app/src
      - ./static:/var/app/static
      - ./templates:/var/app/templates
    stdin_open: true
    tty: true

  poetry_update:
    platform: 'linux/amd64'
    build:
      context: .
      target: poetry_update
    volumes:
      - ./poetry.lock:/var/app/poetry.lock

  lint_and_test:
    platform: 'linux/amd64'
    build:
      context: .
      target: lint_and_test

  format:
    platform: 'linux/amd64'
    build:
      context: .
      target: format
    volumes:
      - ./src:/var/app/src
