# ruff:noqa E501
# ref: https://github.com/pdumoulin/ir-tools/tree/main/ir_library

IR_CODES = {
    "tv": {
        "power": "JgDSAJSVETgSOBI4ERQRFBETEhMSExI4ETkROBITEhMSExEUERQRFBE4EhMSExITERQRFBEUETgSExI4ETkROBI4ETkROBMABgOVlBM2FDYUNhMSEhITEhMSExITNxM2FDYUERMSEhMSExITEhITNxQRExISExITEhITEhM3ExISOBM2FDYTNxM2FDYUAAYBlpMUNRQ2FDYUERMSExEUERQRFDYUNRQ2FBEUERQRFBETEhMRFDYUERQRFBETEhMRFBEUNhQRFDUUNhQ2FDUUNhQ2FAANBQAAAAAAAA==",
        "source": "JgDSAJaTEzcTNhQ2FBETEhMSExITERQ2FDYTNxMRFBEUERQRFBETNxMSExEUERQRFBEUERMSExITNhQ2FDYTNhQ2FDYTNhQABgKWkxQ2FDYTNhQRFBEUERMSExITNhQ2FDYTEhMRFBEUERQRFDYTEhMRFBEUERQRFBEUERMSEzYUNhQ2EzYUNhQ2FDUUAAYClpMTNhQ2FDYTEhMSExEUERQRFDQVNhQ2FBEUERQRExITEhM2FBEUERQRExITERQRFBEUERQ2EzYUNhQ2EzYUNhQ2FAANBQAAAAAAAA==",
    },
    "speaker": {
        "power": "JgBYAAABKJIUERQRFBEUERQRFBEUERQRFDYUNhQ2FDUVNRU1FDYUNhQRFBEUERQRFBEUERQ2FBEUNhQ1FTUVNRQ2FDYUERQ2FAAFFQABKEgUAAxMAAEpSBQADQU=",
        "vol_up": "JgBQAAABKZEUERQRFBEUERQRFBEUERQRFDYUNhQ2FDYUNRU1FTUUNhQ2FBEUERQRFBEUERQ2FBEUERQ2FDUVNRU1FDYUERQ2FAAFFQABKEgUAA0FAAAAAAAAAAA=",
        "vol_down": "JgBQAAABKJEVEBQRFBEVEBQRFRAVEBUQFTUUNhQ2FDYUNRU1FTUUNhQ2FBEUNhQRFBEUERQ1FREUERQ1FRAVNRQ2FDYUERQ2FAAFFQABKEgUAA0FAAAAAAAAAAA=",
        "mute": "JgBYAAABKJIUERQRFBEUERQRFBEUERQRFDYUNhQ2FDYUNhQ1FTUVNRQRFRAVEBU1FBEUERQ2FBEUNhQ2FDYUERQ2FDYUERQ1FQAFFQABKUgUAAxNAAEoSBUADQU=",
    },
    "hdmi_switch": {
        "1": "JgBYAAABKJQSFBIUEhQSExMTFRETExM2EzcUNRQ1FTUUNRQ1FDUVERURFTUVERQRFhAVERURFREUNRURFTUUNRQ1FDUUNhQ1EgAFDwABJ0oSAAxLAAEqSBMADQU=",
        "2": "JgBYAAABKZQSFBIUEhQSFBIUEhMTExM3EjcSNxM3EjcSNxM3EjcSFBIUEhQSNxIUEhQSFBIUEhQSNxI3ExMTNxI3EjcSNxM3EgAFDgABKEkTAAxNAAEmShMADQU=",
        "3": "JgBYAAABKJQUEhIUFBIUEhQSFBIUEhQ1FDUVNRQ1FDUVNRQ1FDUVERU1FBIUNRQSFBIUEhQSFREUEhQ1FREVNRU0FDUVNRU0FQAFDAABJ0oSAAxOAAEqSBQADQU=",
        "4": "JgBgAAABKJQSFBIUEhQSFBIUEhQSFBI3EjUUNxM3EjcSNxM3EjcSFBIUEjcSNxMTExMSFBMTExMTNhMTEhQSNxM3EzYTNhQ1FAAFDQABJ0oTAAxMAAEnShMADEwAASdKEwANBQAAAAAAAAAA",
        "5": "JgBYAAABKpIUEhQSFBIUEhQRFREVERU1FDUUNRU0FTUUNRU0FTUUEhQSFBIUERU1FBIUEhQSFBIUNRQ1FTQVERU1FDUVNBU1FAAFDAABKUkTAAxMAAEoSRQADQU=",
    },
}
